[rpc_endpoints]
"mainnet/automata" = "https://rpc.ata.network"
"mainnet/bob" = "https://rpc.gobob.xyz"
"mainnet/base" = "https://mainnet.base.org"
"mainnet/tbn" = "https://rpc.zero.thebinaryholdings.com"
"mainnet/cyber" = "https://rpc.cyber.co"
"mainnet/ethernity" = "https://mainnet.ethernitychain.io"
"mainnet/funki" = "https://rpc-mainnet.funkichain.com"
"mainnet/hashkeychain" = "https://mainnet.hsk.xyz"
"mainnet/ink" = "https://rpc-gel.inkonchain.com"
"mainnet/lisk" = "https://rpc.api.lisk.com"
"mainnet/lyra" = "https://rpc.lyra.finance"
"mainnet/metal" = "https://rpc.metall2.com"
"mainnet/mint" = "https://rpc.mintchain.io"
"mainnet/mode" = "https://mainnet.mode.network"
"mainnet/op" = "https://mainnet.optimism.io"
"mainnet/orderly" = "https://rpc.orderly.network"
"mainnet/polynomial" = "https://rpc.polynomial.fi"
"mainnet/race" = "https://racemainnet.io"
"mainnet/redstone" = "https://rpc.redstonechain.com"
"mainnet/shape" = "https://mainnet.shape.network/"
"mainnet/soneium" = "https://rpc.soneium.org"
"mainnet/sseed" = "https://mainnet.superseed.xyz"
"mainnet/swan" = "https://mainnet-rpc.swanchain.org"
"mainnet/swell" = "https://swell-mainnet.alt.technology"
"mainnet/unichain" = "https://mainnet.unichain.org"
"mainnet/worldchain" = "https://worldchain-mainnet.g.alchemy.com/public"
"mainnet/xterio-eth" = "https://xterio-eth.alt.technology/"
"mainnet/zora" = "https://rpc.zora.energy"
"mainnet/arena-z" = "https://rpc.arena-z.gg"
"sepolia/base" = "https://sepolia.base.org"
"sepolia/tbn" = "https://rpc.testnet.thebinaryholdings.com"
"sepolia/creator-chain-testnet" = "https://rpc.creatorchain.io"
"sepolia/cyber" = "https://rpc.testnet.cyber.co"
"sepolia/ethernity" = "https://testnet.ethernitychain.io"
"sepolia/funki" = "https://funki-testnet.alt.technology"
"sepolia/ink" = "https://rpc-gel-sepolia.inkonchain.com"
"sepolia/lisk" = "https://rpc.sepolia-api.lisk.com"
"sepolia/metal" = "https://testnet.rpc.metall2.com"
"sepolia/mode" = "https://sepolia.mode.network"
"sepolia/op" = "https://sepolia.optimism.io"
"sepolia/pivotal" = "https://sepolia.pivotalprotocol.com/"
"sepolia/race" = "https://racetestnet.io"
"sepolia/shape" = "https://sepolia.shape.network/"
"sepolia/soneium-minato" = "https://rpc.minato.soneium.org"
"sepolia/unichain" = "https://sepolia.unichain.org"
"sepolia/worldchain" = "https://worldchain-sepolia.g.alchemy.com/public"
"sepolia/zora" = "https://sepolia.rpc.zora.energy"
"sepolia/arena-z-testnet" = "https://rpc.arena-z.t.raas.gelato.cloud"
"sepolia-dev-0/base-devnet-0" = ""
"sepolia-dev-0/oplabs-devnet-0" = ""
op_chain_a = "http://127.0.0.1:9545"
op_chain_b = "http://127.0.0.1:9546"

[profile.default]
src = "src"
script = "scripts"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

fs_permissions = [
  { access='read', path='./configs' },
  { access='read', path='./test' },
  { access='write', path='./deployment.json' }
]

remappings = [
  "@interop-lib/=lib/interop-lib/src/",
  "@solady/=lib/solady/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
